# Generated by Django 5.2.4 on 2025-07-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Отображаемый текст меню', max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Прямой URL')),
                ('named_url', models.CharField(blank=True, max_length=100, verbose_name='Именованный URL')),
                ('menu_name', models.CharField(max_length=50, verbose_name='Системное имя меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['menu_name'], name='menu_menuit_menu_na_afda77_idx'), models.Index(fields=['parent'], name='menu_menuit_parent__af2077_idx')],
                'unique_together': {('menu_name', 'name')},
            },
        ),
    ]
